name: Docker Image CI for GHCR

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username ouadoudev --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . -t ghcr.io/ouadoudev/portfolio:latest
          docker push ghcr.io/ouadoudev/portfolio:latest
